version: "3"

services:

  backendai-db:
    container_name: backendai-local-db
    image: postgres:9.6-alpine
    ports:
      - "8100:5432"
    environment:
      - POSTGRES_PASSWORD=develove
      - POSTGRES_DB=backend

  backendai-redis:
    container_name: backendai-local-redis
    image: redis:latest
    ports:
      - "8110:6379"

  backendai-etcd:
    container_name: backendai-local-etcd
    image: quay.io/coreos/etcd:v3.2.15
    volumes:
      - /tmp/backend.ai/etcd-data:/etcd-data
    ports:
      - "8120:2379"
    command: >
      /usr/local/bin/etcd
      --name backendai-etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster backendai-etcd=http://0.0.0.0:2380
      --initial-cluster-token backendai-etcd-token
      --initial-cluster-state new
      --auto-compaction-retention 1
