version: "3"

services:

  backendai-redis:
    container_name: backendai-local-redis
    image: redis:latest
    ports:  # for host-side debugging
      - "6389:6379"

  backendai-db:
    container_name: backendai-local-db
    image: postgres:9.6-alpine
    ports:  # for host-side debugging
      - "5442:5432"
    environment:
      - POSTGRES_PASSWORD=develove
      - POSTGRES_DB=backend

  backendai-etcd:
    container_name: backendai-local-etcd
    image: quay.io/coreos/etcd:v3.1.5
    volumes:
      - /tmp/etcd-data:/etcd-data
    ports:  # for host-side debugging
      - "2379:2379"
      - "2380:2380"
    command: >
      /usr/local/bin/etcd
      --name backendai-etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster backendai-etcd=http://0.0.0.0:2380
      --initial-cluster-token backendai-etcd-token
      --initial-cluster-state new
      --auto-compaction-retention 1
